name: Distribution Builds

on:
  pull_request:
    types:
      - closed
  # Automatically on every tag starting with v
  push:
    tags:
      - v*
  # Manual dispatch for testing
  workflow_dispatch:

jobs:
  build:
    env:
      ITCH_PROJECT: 'fourlastor/rebirth'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: jdno/setup-butler@v1
      - name: Build
        uses: ./.github/actions/gradle-build
        with:
          arguments: html:dist
      - name: Deploy 🚀
        if: github.event.pull_request.merged == true || startsWith(github.ref, 'refs/tags/')
        run: butler push html/build/dist $ITCH_PROJECT:html
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
